name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:       # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: ronaksharma2908
          svg_out_path: dist/snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
         publish_dir:.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          #FUN ANIMATED SNAKE
          
